version: '3.9'

services:
  # Main service to run the program
  apache-pyspark:
    # image: python:3.11.0b4-slim-buster
    image: pytorch/pytorch:latest
    volumes:
      - ./myTwitter.py:/project/myTwitter.py
      - ./config.ini:/project/config.ini
    ports:
      - 80:80
    working_dir: /project
    # python3 -m pip install torch===1.3.1 torchvision===0.4.2 -f https://download.pytorch.org/whl/torch_stable.html
    command: >
      sh -c "python3 -m pip install --upgrade pip&&
             python3 -m pip install tweepy==4.10.0 kafka-python==2.0.1 transformers==4.20.1&&
             sleep 2m &&
             python myTwitter.py"
    depends_on:
      - logstash

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.2
    container_name: kafka
    ports:
      - "9092:9092"
      - '9093:9093'
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://0.0.0.0:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  # logstash to read from kafka
  logstash:
    image: logstash:8.3.2
    container_name: logstash
    volumes:
      - ./logstash.conf:/config-dir/logstash.conf
    restart: always
    command: logstash -f /config-dir/logstash.conf
    ports:
      - 9600:9600
      - 7777:7777
    links:
      - elasticsearch
      - kafka
    depends_on:
      - kafka
      - elasticsearch     

  # Standalone elasticsearch
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.3.2
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    mem_limit: 1073741824
    ports:
      - 9200:9200

  # For visuvalisation of data in Elasticsearch
  kibana:
    container_name: kibana
    image: kibana:8.3.2
    environment:
      - MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED=false
    ports:
      - 5601:5601
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

volumes:
  zookeeper_data:
  kafka_data:
